
//
export const HOME = 'HOME'
//
export const DEPARTAMENTO_INDEX = 'DEPARTAMENTO_INDEX'
export const DEPARTAMENTO_EDIT = 'DEPARTAMENTO_EDIT'
export const DEPARTAMENTO_CREATE = 'DEPARTAMENTO_CREATE';
//
export const FUNCIONARIO_INDEX = 'FUNCIONARIO_INDEX'
export const FUNCIONARIO_EDIT = 'FUNCIONARIO_EDIT'
export const FUNCIONARIO_CREATE = 'FUNCIONARIO_CREATE';
//
export const FERIAS_INDEX = 'FERIAS_INDEX'
export const FERIAS_EDIT = 'FERIAS_EDIT'
export const FERIAS_CREATE = 'FERIAS_CREATE';
//
export const RELATORIO_UNIDADE = 'RELATORIO_UNIDADE'
export const RELATORIO_DEPARTAMENTO = 'RELATORIO_DEPARTAMENTO'
export const RELATORIO_FUNCIONARIO = 'RELATORIO_FUNCIONARIO'

